services:
    sopinet_user_preferences.twig.base_extension:
        class: Sopinet\UserPreferencesBundle\Twig\BaseExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    sopinet_user_preferences:
        class: Sopinet\UserPreferencesBundle\Service\PreferencesHelper
        arguments: ["@service_container"]